/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Librarybook.ui;

import com.Librarybook.DAO.PhieuMuonCTDAO;
import com.Librarybook.DAO.PhieuMuonDAO;
import com.Librarybook.DAO.SachDAO;
import com.Librarybook.entity.Sach;
import com.Librarybook.util.Auth;
import com.Librarybook.util.MsgBox;
import com.Librarybook.util.Ximage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ManHinhChinhJDialog extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinhJDialog
     */
    public ManHinhChinhJDialog() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblmuonsach = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbodanhmucsach = new javax.swing.JComboBox();
        cbotheloai = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltracuusach = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnhethong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniMatKhau = new javax.swing.JMenuItem();
        mniketThuc = new javax.swing.JMenuItem();
        jmnquanli = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mniSach = new javax.swing.JMenuItem();
        lbltheloai = new javax.swing.JMenuItem();
        lbldanhmucsach = new javax.swing.JMenuItem();
        lbldanhsachmuon = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnhotro = new javax.swing.JMenu();
        mniTuVan = new javax.swing.JMenuItem();
        mniGiaDapThacMac = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LibraryBooks");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1464, 73));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1353, 601));

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel12.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Trang Chủ", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/tutorial.png")), jPanel2); // NOI18N

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/tutorial (1).png"))); // NOI18N
        jLabel5.setText("Thông Tin Sách Có Thể Mượn");

        tblmuonsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Nhà Xuất bản"
            }
        ));
        jScrollPane3.setViewportView(tblmuonsach);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/xoa.png"))); // NOI18N
        jButton4.setText("Xóa");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(79, 79, 79))))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/schedule.png"))); // NOI18N
        jLabel6.setText("Ngày Hẹn Trả");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "10" }));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/book (1).png"))); // NOI18N
        jButton3.setText("Xác Nhận");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addGap(57, 57, 57)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Mượn Sách", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/books.png")), jPanel3); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbodanhmucsach.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbotheloai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/eraser.png"))); // NOI18N
        jButton1.setText("Reset");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cbodanhmucsach, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(cbotheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbodanhmucsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbotheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbltracuusach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Danh Mục", "Thể Loại"
            }
        ));
        jScrollPane1.setViewportView(tbltracuusach);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/book.png"))); // NOI18N
        jButton2.setText("Chi Tiết Sách");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Tra Cứu Sách", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/research.png")), jPanel4); // NOI18N

        jTabbedPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Thống kê Sách", jPanel11);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Thống kê Tiền Phạt", jPanel10);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Thống Kê", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/statistics.png")), jPanel5); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1260, 610));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("Hệ Thống Quản Lí Thư Viện");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        lblClock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1250, 30));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("LibraryBooks");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Trường Cao Đẳng FPT Polytechniec - Cơ Sở 3");

        lbldongho.setBackground(new java.awt.Color(255, 255, 255));
        lbldongho.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        lbldongho.setForeground(new java.awt.Color(255, 102, 51));
        lbldongho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/alarm-clock.png"))); // NOI18N
        lbldongho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbldongho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbldonghoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setText("LoGoFPT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(331, 331, 331)))
                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, -1));

        jmnhethong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/icons8-home-24.png"))); // NOI18N
        jmnhethong.setText("Hệ Thống");
        jmnhethong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnhethongActionPerformed(evt);
            }
        });

        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/logout.png"))); // NOI18N
        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jmnhethong.add(mniDangXuat);

        mniMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/refresh.png"))); // NOI18N
        mniMatKhau.setText("Đổi Mật Khẩu");
        mniMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMatKhauActionPerformed(evt);
            }
        });
        jmnhethong.add(mniMatKhau);

        mniketThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/ending.png"))); // NOI18N
        mniketThuc.setText("Kết Thúc");
        mniketThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketThucActionPerformed(evt);
            }
        });
        jmnhethong.add(mniketThuc);

        jMenuBar1.add(jmnhethong);

        jmnquanli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/businessman.png"))); // NOI18N
        jmnquanli.setText("Quản Lí");
        jmnquanli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnquanliActionPerformed(evt);
            }
        });

        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/employee.png"))); // NOI18N
        mniNhanVien.setText("Nhân Viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        jmnquanli.add(mniNhanVien);

        mniSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/open-book.png"))); // NOI18N
        mniSach.setText("Sách");
        mniSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSachActionPerformed(evt);
            }
        });
        jmnquanli.add(mniSach);

        lbltheloai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/poem.png"))); // NOI18N
        lbltheloai.setText("Thể Loại");
        lbltheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltheloaiActionPerformed(evt);
            }
        });
        jmnquanli.add(lbltheloai);

        lbldanhmucsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/director.png"))); // NOI18N
        lbldanhmucsach.setText("Danh Mục Sách");
        lbldanhmucsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbldanhmucsachActionPerformed(evt);
            }
        });
        jmnquanli.add(lbldanhmucsach);

        lbldanhsachmuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/bill.png"))); // NOI18N
        lbldanhsachmuon.setText("Danh Sách Mượn");
        lbldanhsachmuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbldanhsachmuonActionPerformed(evt);
            }
        });
        jmnquanli.add(lbldanhsachmuon);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/publisher.png"))); // NOI18N
        jMenuItem1.setText("Nhà Xuất Bản");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmnquanli.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/author.png"))); // NOI18N
        jMenuItem2.setText("Tác Giả");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnquanli.add(jMenuItem2);

        jMenuBar1.add(jmnquanli);

        jmnhotro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/consultant-services.png"))); // NOI18N
        jmnhotro.setText("Hỗ TRợ");

        mniTuVan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/customer-support.png"))); // NOI18N
        mniTuVan.setText("Tư Vấn");
        mniTuVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTuVanActionPerformed(evt);
            }
        });
        jmnhotro.add(mniTuVan);

        mniGiaDapThacMac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/consultant-services.png"))); // NOI18N
        mniGiaDapThacMac.setText("Giải Đáp Thắc Mắc");
        mniGiaDapThacMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGiaDapThacMacActionPerformed(evt);
            }
        });
        jmnhotro.add(mniGiaDapThacMac);

        jMenuBar1.add(jmnhotro);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSachActionPerformed
        // TODO add your handling code here:
        this.openSach();
    }//GEN-LAST:event_mniSachActionPerformed

    private void mniGiaDapThacMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGiaDapThacMacActionPerformed
        // TODO add your handling code here:
        this.openTuvanThacMac();
    }//GEN-LAST:event_mniGiaDapThacMacActionPerformed

    private void lblClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorAdded

    private void lbldonghoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbldonghoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbldonghoAncestorAdded

    private void jmnhethongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnhethongActionPerformed
        // TODO add your handling code here:
        this.DangXuat();
    }//GEN-LAST:event_jmnhethongActionPerformed

    private void mniMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMatKhauActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_mniMatKhauActionPerformed

    private void mniketThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketThucActionPerformed
        // TODO add your handling code here:
        this.KetThuc();
    }//GEN-LAST:event_mniketThucActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void lbltheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbltheloaiActionPerformed
        // TODO add your handling code here:
        this.OpenTheLoai();
    }//GEN-LAST:event_lbltheloaiActionPerformed

    private void lbldanhmucsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbldanhmucsachActionPerformed
        // TODO add your handling code here:
        this.OpenDanhMucSach();
    }//GEN-LAST:event_lbldanhmucsachActionPerformed

    private void jmnquanliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnquanliActionPerformed
        // TODO add your handling code here:
        this.openDanhSachMuon();
    }//GEN-LAST:event_jmnquanliActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        this.DangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniTuVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTuVanActionPerformed
        // TODO add your handling code here:
        this.openTuVan();
    }//GEN-LAST:event_mniTuVanActionPerformed

    private void lbldanhsachmuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbldanhsachmuonActionPerformed
        // TODO add your handling code here:
        this.openDanhSachMuon();
    }//GEN-LAST:event_lbldanhsachmuonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.openNhaXuatBan();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.openTacGia();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinhJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbodanhmucsach;
    private javax.swing.JComboBox cbotheloai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenu jmnhethong;
    private javax.swing.JMenu jmnhotro;
    private javax.swing.JMenu jmnquanli;
    private javax.swing.JLabel lblClock;
    private javax.swing.JMenuItem lbldanhmucsach;
    private javax.swing.JMenuItem lbldanhsachmuon;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenuItem lbltheloai;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniGiaDapThacMac;
    private javax.swing.JMenuItem mniMatKhau;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniSach;
    private javax.swing.JMenuItem mniTuVan;
    private javax.swing.JMenuItem mniketThuc;
    private javax.swing.JTable tblmuonsach;
    private javax.swing.JTable tbltracuusach;
    // End of variables declaration//GEN-END:variables

    SachDAO sdao = new SachDAO();
    PhieuMuonDAO pmdao = new PhieuMuonDAO();
    PhieuMuonCTDAO ctpmdao = new PhieuMuonCTDAO();

    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(Ximage.getAppIcon());

        new FormManHinhChao(null, true).setVisible(true);
        new FormMHDangNhap(null, true).setVisible(true);

        new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");//hh : giờ mm : phút ss: giây a : sáng chiều
                String text = formater.format(now);
                lbldongho.setText(text);
            }
        }).start();
        this.fillTableMuonSach();
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new FormDoiMatKhau(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void DangXuat() {
        if (Auth.isLogin()) {
            Auth.clear();
            new FormMHDangNhap(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void KetThuc() {
        if (MsgBox.confirm(this, "Bạn Có Muốn Kết Thúc Làm Việc ?")) {
            System.exit(0);
        }
    }

    void openNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienJDialog(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void openSach() {
        if (Auth.isLogin()) {
            new QuanLySachJDialog(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenDanhMucSach() {
        if (Auth.isLogin()) {
            new FormDanhMucSach(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenTheLoai() {
        if (Auth.isLogin()) {
            new FormTheLoaiSach(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void openTuVan() {
        if (Auth.isLogin()) {
            new HoTroForm(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void openTuvanThacMac() {
        if (Auth.isLogin()) {
            new HoTroForm(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void openDanhSachMuon() {
        if (Auth.isLogin()) {
            new PhieuMuonJDialog(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    private void openNhaXuatBan() {
        if (Auth.isLogin()) {
            new NXBJDialog(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    private void openTacGia() {
        if (Auth.isLogin()) {
            new TacGiaJDialog(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    void fillTableMuonSach() {
        DefaultTableModel model = (DefaultTableModel) tblmuonsach.getModel();
        model.setRowCount(0);
        try {
            List<Sach> list = sdao.selectAll();
            for (Sach s : list) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getTacGia(),
                    s.getNXB()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
        fillTableTraCuuSach();
    }

    void fillTableTraCuuSach() {
        DefaultTableModel model = (DefaultTableModel) tbltracuusach.getModel();
        model.setRowCount(0);
        try {
            List<Sach> list = sdao.selectAll();
            for (Sach s : list) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getTacGia(),
                    s.getMaDMSach(),
                    s.getMaTheLoai()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
    }

}
